// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8TrCBS8vu0Tt-5te2IhytRrxGDc2mVb0',
    appId: '1:1024270967652:web:bf7d515cb869b5b074d071',
    messagingSenderId: '1024270967652',
    projectId: 'decathdam',
    authDomain: 'decathdam.firebaseapp.com',
    storageBucket: 'decathdam.firebasestorage.app',
    measurementId: 'G-L8SD8HJFNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUFYBofArqsQ4FSjYpa_qHOjQqUPyT1Y',
    appId: '1:1024270967652:android:6011bb5130e2829674d071',
    messagingSenderId: '1024270967652',
    projectId: 'decathdam',
    storageBucket: 'decathdam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXs69-29ynaIDMlCJyFSal4wH0MLMkJzo',
    appId: '1:1024270967652:ios:62afb0c85cb43b2b74d071',
    messagingSenderId: '1024270967652',
    projectId: 'decathdam',
    storageBucket: 'decathdam.firebasestorage.app',
    iosBundleId: 'com.decathdam.decathdam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXs69-29ynaIDMlCJyFSal4wH0MLMkJzo',
    appId: '1:1024270967652:ios:62afb0c85cb43b2b74d071',
    messagingSenderId: '1024270967652',
    projectId: 'decathdam',
    storageBucket: 'decathdam.firebasestorage.app',
    iosBundleId: 'com.decathdam.decathdam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8TrCBS8vu0Tt-5te2IhytRrxGDc2mVb0',
    appId: '1:1024270967652:web:261f5cdd9bc0d26174d071',
    messagingSenderId: '1024270967652',
    projectId: 'decathdam',
    authDomain: 'decathdam.firebaseapp.com',
    storageBucket: 'decathdam.firebasestorage.app',
    measurementId: 'G-T3BEMR6LSQ',
  );
}
